services:
  mysql:
    container_name: javaAssignment_mysql_container
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    container_name: javaAssignment_server_container
    image: nayoun340/java-assignment
    ports:
      - 8080:8080
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
