name: 'CI_CD'

on:
  pull_request:
    branches: [ main ]

jobs:
  cicd:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: 깃헙 코드를 VM으로 복사
        uses: actions/checkout@v4

      - name: 깃헙 액션의 VM에 자바 설치중 ...
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: aws docker-compose.yml 설치
        run: |
          echo "${{ secrets.SECRET_DOCKER_COMPOSE_YML }}" > docker-compose.yml
        shell: bash

      - name: aws 배포용 yml 파일 생성
        run: |
          cd ./src/main/resources 
          echo "${{ secrets.SECRET_APPLICATION_YML }}" > ./application.yml
        shell: bash

      - name: MySQL 도커 컨테이너 실행
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: ${{secrets.SECRET_DB_NAME}}
          mysql root password: ${{secrets.SECRET_DB_PASSWORD}}

      - name: 빌드 및 테스트 코드 돌리는중 ...
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: 도커 이미지 빌드 및 푸시
        run: |
          docker login -u ${{secrets.SECRET_DOCKER_ID}} -p ${{secrets.SECRET_DOCKER_TOKEN}}
          docker build -t ${{secrets.SECRET_DOCKER_ID}}/${{secrets.SECRET_DOCKER_REPO}} .
          docker push ${{secrets.SECRET_DOCKER_ID}}/${{secrets.SECRET_DOCKER_REPO}}

      - name: ec2에 docker-compose.yml 파일 복사시키기
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.SECRET_AWS_HOST}}
          key: ${{secrets.SECRET_AWS_KEY}}
          username: ubuntu
          source: ./docker-compose.yml
          target: ~/docker-compose.yml

      - name: executing remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SECRET_AWS_HOST}}
          key: ${{secrets.SECRET_AWS_KEY}}
          username: ubuntu
          script: |
            sudo systemctl restart docker
            docker login -u ${{secrets.DOCKER_HUB_ID}} -p ${{secrets.DOCKER_HUB_TOKEN}}
            sudo docker pull ${{secrets.DOCKER_HUB_ID}}/${{secrets.DOCKER_HUB_REPO}}            
            cd ~/docker-compose.yml
            sudo docker-compose down
            sudo docker-compose up -d
            sudo docker image prune -f
